# API Contract Hardening - CI/CD Pipeline
name: API Contract Enforcement

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/routes/**'
      - 'backend/tests/**'
      - 'backend/main.py'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/routes/**'
      - 'backend/tests/**'
      - 'backend/main.py'

jobs:
  api-contract-hardening:
    name: API Contract Hardening
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install pytest pytest-asyncio httpx

    - name: Run API Contract Tests
      run: |
        cd backend
        python -m pytest tests/test_contract_http_comprehensive.py -v --tb=short --junit-xml=contract-test-results.xml
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload Contract Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: contract-test-results-${{ matrix.python-version }}
        path: backend/contract-test-results.xml

    - name: Scan for Contract Violations
      run: |
        python3 -c "
        import re
        import sys
        from pathlib import Path
        
        print('🔍 Scanning for API contract violations...')
        violations = []
        patterns = [
            (r'raise HTTPException\(', 'Direct HTTPException usage'),
            (r'return\s+\{\s*[\"\'']error[\"\'']:\s*[^}]+\}', 'Direct error dict returns'),
            (r'return\s+\{\s*[\"\'']status[\"\'']:\s*[\"\'']error[\"\'']', 'Status error returns'),
            (r'JSONResponse\([^)]*status_code\s*=\s*[45]\d\d[^)]*[\"\'']error[\"\'']', 'JSONResponse with errors'),
        ]
        
        routes_dir = Path('backend/routes')
        if not routes_dir.exists():
            print('❌ Backend routes directory not found')
            sys.exit(1)
        
        for py_file in routes_dir.glob('*.py'):
            if py_file.name.startswith('__'):
                continue
            try:
                with open(py_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                for pattern, description in patterns:
                    matches = list(re.finditer(pattern, content, re.MULTILINE | re.DOTALL))
                    for match in matches:
                        line_num = content[:match.start()].count('\n') + 1
                        violations.append({
                            'file': str(py_file),
                            'line': line_num,
                            'type': description,
                            'match': match.group()[:60]
                        })
            except Exception as e:
                print(f'Warning: Could not scan {py_file}: {e}')
        
        if violations:
            print(f'❌ Found {len(violations)} contract violations:')
            # Group by file for cleaner output
            by_file = {}
            for v in violations:
                if v['file'] not in by_file:
                    by_file[v['file']] = []
                by_file[v['file']].append(v)
            
            for file_path, file_violations in sorted(by_file.items()):
                print(f'\\n📁 {file_path}:')
                for v in file_violations[:5]:  # Show first 5 per file
                    print(f'  Line {v[\"line\"]}: {v[\"type\"]} - {v[\"match\"]}')
                if len(file_violations) > 5:
                    print(f'  ... and {len(file_violations) - 5} more violations')
            
            print(f'\\n📊 Summary: {len(by_file)} files with {len(violations)} total violations')
            print('📖 See API_CONTRACT_GUIDE.md for proper exception handling patterns')
            
            # Allow up to 10 violations for gradual migration
            if len(violations) > 500:  # Current baseline: ~400 violations
                print(f'❌ Too many violations ({len(violations)} > 500 limit)')
                print('🔧 Please fix violations before merging')
                sys.exit(1)
            else:
                print(f'⚠️  {len(violations)} violations detected but within threshold (≤500)')
                print('🎯 Goal: Reduce violations in each PR')
        else:
            print('✅ No contract violations detected')
        "

    - name: Check Response Model Annotations
      run: |
        python3 -c "
        import re
        import sys
        from pathlib import Path
        
        print('📋 Checking response_model annotations...')
        routes_dir = Path('backend/routes')
        
        # Critical files that MUST have response_model annotations
        critical_files = [
            'enhanced_api.py',
            'production_health_routes.py', 
            'unified_api.py',
            'optimized_api_routes.py'
        ]
        
        missing_annotations = []
        
        for filename in critical_files:
            file_path = routes_dir / filename
            if not file_path.exists():
                print(f'⚠️  Critical file not found: {filename}')
                continue
            
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                route_pattern = r'@router\.(get|post|put|delete|patch)\s*\([^)]*\)\s*\\n\s*(?:async\s+)?def\s+(\w+)'
                response_model_pattern = r'response_model\s*='
                
                for match in re.finditer(route_pattern, content, re.MULTILINE):
                    method = match.group(1)
                    func_name = match.group(2)
                    line_start = content[:match.start()].count('\\n') + 1
                    
                    # Skip certain endpoints
                    if func_name in ['health_check', 'debug_endpoint', 'system_debug']:
                        continue
                    
                    decorator_start = content.rfind('@router', 0, match.start())
                    decorator_end = match.end()
                    decorator_section = content[decorator_start:decorator_end]
                    
                    if not re.search(response_model_pattern, decorator_section):
                        missing_annotations.append({
                            'file': filename,
                            'function': func_name,
                            'method': method,
                            'line': line_start
                        })
            except Exception as e:
                print(f'Warning: Could not check {file_path}: {e}')
        
        if missing_annotations:
            print(f'❌ Found {len(missing_annotations)} missing response_model annotations:')
            for annotation in missing_annotations:
                print(f'  {annotation[\"file\"]}:{annotation[\"line\"]} - {annotation[\"method\"]} {annotation[\"function\"]}')
            print('\\n📖 Add response_model= parameter to route decorators')
            sys.exit(1)
        else:
            print('✅ All critical routes have response_model annotations')
        "

    - name: Performance Regression Check
      run: |
        cd backend
        python -c "
        import time
        import requests
        import subprocess
        import sys
        
        print('⚡ Starting performance regression check...')
        
        # Start server in background for performance testing
        print('🚀 Starting test server...')
        server = subprocess.Popen([
            sys.executable, '-m', 'uvicorn', 'main:app', 
            '--host', '127.0.0.1', '--port', '8001'
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        # Wait for server to start
        time.sleep(3)
        
        try:
            # Test contract endpoints for performance regression
            endpoints = [
                '/api/health',
                '/api/analytics', 
                '/api/predictions',
                '/api/props'
            ]
            
            performance_issues = []
            
            for endpoint in endpoints:
                try:
                    start_time = time.time()
                    response = requests.get(f'http://127.0.0.1:8001{endpoint}', timeout=5)
                    elapsed = time.time() - start_time
                    
                    if response.status_code == 200:
                        # Check if response follows contract
                        data = response.json()
                        if not all(key in data for key in ['success', 'data', 'error']):
                            performance_issues.append(f'{endpoint}: Invalid contract format')
                        elif elapsed > 2.0:  # 2 second threshold
                            performance_issues.append(f'{endpoint}: Slow response ({elapsed:.2f}s)')
                        else:
                            print(f'✅ {endpoint}: {elapsed:.3f}s')
                    else:
                        print(f'⚠️  {endpoint}: HTTP {response.status_code}')
                except requests.RequestException as e:
                    print(f'⚠️  {endpoint}: Connection error - {e}')
                except Exception as e:
                    print(f'⚠️  {endpoint}: Test error - {e}')
            
            if performance_issues:
                print(f'❌ Performance regression detected:')
                for issue in performance_issues:
                    print(f'  {issue}')
                sys.exit(1)
            else:
                print('✅ No performance regressions detected')
            
        finally:
            server.terminate()
            server.wait(timeout=5)
        "

    - name: Generate Contract Compliance Report
      if: always()
      run: |
        python3 -c "
        import json
        import sys
        from datetime import datetime
        from pathlib import Path
        
        print('📊 Generating contract compliance report...')
        
        # Count violations by type
        violations_by_type = {}
        routes_dir = Path('backend/routes')
        
        if routes_dir.exists():
            for py_file in routes_dir.glob('*.py'):
                if py_file.name.startswith('__'):
                    continue
                try:
                    with open(py_file, 'r') as f:
                        content = f.read()
                    if 'raise HTTPException(' in content:
                        violations_by_type.setdefault('HTTPException', []).append(str(py_file))
                    if 'return {\"error\"' in content or 'return {\"status\": \"error\"' in content:
                        violations_by_type.setdefault('Direct Error Returns', []).append(str(py_file))
                except:
                    continue
        
        report = {
            'timestamp': datetime.utcnow().isoformat(),
            'total_route_files': len(list(routes_dir.glob('*.py'))) if routes_dir.exists() else 0,
            'violations_by_type': violations_by_type,
            'total_violations': sum(len(files) for files in violations_by_type.values()),
            'compliance_percentage': 0
        }
        
        if report['total_route_files'] > 0:
            compliant_files = report['total_route_files'] - len(set().union(*violations_by_type.values()))
            report['compliance_percentage'] = (compliant_files / report['total_route_files']) * 100
        
        # Save report
        with open('contract-compliance-report.json', 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f'📈 Contract Compliance: {report[\"compliance_percentage\"]:.1f}%')
        print(f'📁 Files checked: {report[\"total_route_files\"]}')
        print(f'⚠️  Total violations: {report[\"total_violations\"]}')
        
        for violation_type, files in violations_by_type.items():
            print(f'  {violation_type}: {len(files)} files')
        "

    - name: Upload Compliance Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: contract-compliance-report
        path: contract-compliance-report.json

  notification:
    name: Contract Status Notification
    runs-on: ubuntu-latest
    needs: api-contract-hardening
    if: always()

    steps:
    - name: Notify Contract Status
      run: |
        if [ "${{ needs.api-contract-hardening.result }}" == "success" ]; then
          echo "✅ API Contract Hardening: PASSED"
          echo "🎯 All contract tests passed and violations within threshold"
        else
          echo "❌ API Contract Hardening: FAILED"
          echo "🔧 Please review contract violations before merging"
        fi
